apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testApp1
spec:
  destination:
    name: ''
    namespace: test-namespace
    server: 'https://kubernetes.default.svc'
  source:
    path: path/sub-path
    repoURL: ''
    targetRevision: HEAD
  project: test
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testApp2
spec:
  destination:
    name: ''
    namespace: test-namespace
    server: 'https://kubernetes.default.svc'
  source:
    path: path/sub-path
    repoURL: 'h'
    targetRevision: HEAD
    plugin:
      name: kustomize-build-with-params
      env:
        - name: KUSTOMIZE_PLUGIN_HOME
          value: /custom/kustomize/plugins
  project: test
